### PR TITLE
feat: initial commit

### PR DESCRIPTION
**Pull request by reecemcd**
Initial Degen API commit. View this [fork here](https://github.com/reecemcd/degen-api).

# About

This project is built with [NestJS](https://docs.nestjs.com/) using the [fastify](https://docs.nestjs.com/techniques/performance) adapter. The project is maintained as an [NX project](https://nx.dev/) and all dependency upgrades should be handled via [NX cli migrations](https://nx.dev/l/r/core-concepts/updating-nx). View the NX documentation on how to leverage it to execute operations like [serving](https://nx.dev/l/r/cli/serve), [linting](https://nx.dev/l/r/cli/lint), [testing](https://nx.dev/l/r/cli/test), [building](https://nx.dev/l/r/cli/build), and even [generating new code](https://nx.dev/l/r/nest/overview).

# Core Features

This API comes configured with all of the following:

- Eslint for linting
- Prettier for formatting
- Jest for tests
- Husky & Commitlint for commit hooks and linting
- Standard-version for changelog/version management
- NestJS API and all of its awesome patterns (modules, DI, interceptors, guards, etc...)
- Typegoose & nestjs-typegoose for DB models
- Discord.js & discord-nestjs for discord integration
- Class-transformer & class-validator for validation
- Winston and nest-winston for logging in different formats to different transports per env
- Auto-generated OpenAPI swagger docs
- Terminus health check endpoint
- Validated env vars via the APIConfig object
- Custom request logging interceptor
- Custom error logging exception filter
- Docker-compose to spin up local service dependencies like mongo

And more with much more to come!

# Degen Features

Included is a POAP feature module with models, DTOs, services, and controllers for POAP Admin and POAP Event management via REST APIs. API Key auth and guards will be soon to follow on these. We'll soon demo these features by integrating the new degen-web project with this API.

# Documentation

Included is documentation on getting started as well as architecture guidelines that outline common patterns and library integrations.

Read said [API docs here](https://github.com/reecemcd/degen-api/blob/main/docs/architecture/degen-api-style.md) for more details on all of the above. Reach out or comment with any questions!

### CODE REVIEW

**Comment by nonsensecodes** [comment]
Hey @reecemcd, so you weren't party to the über fun convos we had about commit hooks and husky, but as a team, we opted to avoid husky altogether. If you think this is pertinent to development, we can certainly revisit and discuss. Husky aside, for logging, we use LogDNA. If it makes sense to do so, you can pull the `log.ts` file from the main DEGEN repo to integrate here, and forego Winston altogether. And while I understand ORMs are popular, when working with NoSQL DBs, they're largely unnecessary. Ultimately, we want to reduce dependencies as much as possible. Can you do the work without these particular tools and reduce the overhead in the code?

**Comment by reecemcd** [comment]
> Hey @reecemcd, so you weren't party to the über fun convos we had about commit hooks and husky, but as a team, we opted to avoid husky altogether. If you think this is pertinent to development, we can certainly revisit and discuss.

I am not sure how you were using git hooks previously as they can be used to do basically anything. I prefer to use them exclusively to lint commit messages and to run auto-fix capable formatting (via prettier in this case). So essentially to ensure commit messages and code that makes it to the repo is all formatted consistently. There is essentialy zero overhead added to do these simple checks. **I would agree that using git hooks to run tests or builds before commits is a horrible pattern that should be left to CI pipelines.** If y'all don't like the [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/) format or commit linting I think that is OK, but I'd be happy to talk about its benefits. I can't see a reason why you wouldn't want to use hooks to auto format committed code consistently.

> Husky aside, for logging, we use LogDNA. If it makes sense to do so, you can pull the `log.ts` file from the main DEGEN repo to integrate here, and forego Winston altogether.

I disagree completely with ditching Winston and this touches on a point I will make later, but Winston is well established library that does everything you all are trying to do in that `log.ts` but in more flexible and extensible ways. As I documented, Winston comes with a [built in LogDNA transport](https://github.com/winstonjs/winston/blob/master/docs/transports.md) and it makes it super easy to only log to LogDNA in prod mode/upper envs. It has a pattern to format logs different per env which means we can make logs more useful for developers during local dev work. It also has its transport pattern to determine where and how logs get written per env. We can log to the console locally and LogDNA + whatever tracing solution we go with (Sentry? [done](https://github.com/winstonjs/winston/blob/master/docs/transports.md#sentry-transport)) and more as need. It provides us with valuable flexibility. The same cannot be said for the existing logger since its hard coupled to LogDNA. haha I still cannot start the bot locally because I have not setup an account to get a key, which imo should not be required for local dev.

On top of this because I only leveraged it via NestJS' logger abstraction here its essentially a one line change to swap it out for a different (something like pino maybe) or [custom logger service](https://docs.nestjs.com/techniques/logger#injecting-a-custom-logger) down the road if needed. So the cost here is essentially nothing for only big dynamic configuration rewards and free integrations. For all of these reasons I can't really see why you would want to replace it. I'd be happy to talk through this one some more if you have questions or think I'm missing something.

> And while I understand ORMs are popular, when working with NoSQL DBs, they're largely unnecessary. 

I'm a little bit more willing to accept and implement this change but I'd push back with a few points here:
- Typegoose/Mongoose aren't massive ORMs with custom caching layers in the traditional sense like you might be averse to as its essentially just a modelling tool meant to give us a nice way to represent properly typed mongo data as well as validate it. The querying API here is quite similar to that of the native driver (because you are essentially still using it under the hood for most of those methods).
- Typegoose plays very nicely with the full-on typescript-leveraging-decorators nature of NestJS, we can inject collections and query against them without needing to pass around a DB connection.
- Typegoose models can be extended with NestJS [mapped types](https://docs.nestjs.com/openapi/mapped-types) making request/response DTO definitions easier to define and validation enforcement more consistent and uniform with less spaghetti and overhead.
- Typegoose lets us keep model definitions isolated to single file locations reducing maintenance overhead. From a single model file anyone can tell everything they need to know about a collection including required properties, how they are validated, and even description comments that will be rendered in OpenAPI docs if the model is ever used as request/result objects in basic CRUD operations. I find this much more clean and approachable than just having to guess what collections exist and what their shape and types look like. I eventually found some jsonSchema files in the bot today but can't for the life of me see how they are used anywhere. The problems I have heard y'all have with data consistency recently would be completely solved with the patterns used here and how they integrate with NestJS at large.

Basically, again, if we remove it and go with just the native driver, in order to realize all of these same benefits....we'd just end up having to write our own crappier versions of the same tools and I don't think those things are worth our focus or effort right now (or arguably ever).

> Ultimately, we want to reduce dependencies as much as possible.

I 100% agree with you here to a point. I am definitely against adding young new libraries or old poorly maintained libraries as dependencies. But extremely popular massively supported libraries that provide big benefits should not be something to avoid out of paranoia. In doing so you are just ensuring yourself massive tech debt and future headaches as you attempt to re-invent the wheel with custom in-house solutions that have not seen the same testing or run into the same production edge cases the most popular battle hardened libraries have. I've been there myself, I've regretfully left projects of my own like that, and I've had to maintain that legacy codebase dozens of times. I get that there is nuance here but libraries with 8+ million downloads a week aren't going anywhere anytime soon. Issues will be handled swiftly and we'll have years of headroom to migrate off of them if that time comes when it is relevant to the project.

There are even some cases where I would prefer to use even a small sparsely maintained existing 3rd party library if it is simple enough _because it already implements something in the same way we would have implemented it had we not used it._ There is no danger in this scenario. If we run into issues or they drop support for it, ok, we haven't lost any work or effort and just write our own nearly identical solution then or better yet fork that basic one we've been using. nest-winston and nestjs-typegoose are prime examples of this case as they are both essentially miniscule single NestJS modules that serve as helpers for interacting with their respective libraries via NestJS DI. We could rewrite them in the exact same way in every project or just leverage those to avoid the extra work until we need to.

Ultimately, I agree we should use our best judgement when introducing new open source libraries, but they are tools we should leverage when there are great benefits to be had. If we didn't then this argument slips all the way back down through C, assembly language, back to binary...

**Comment by amaredeus** [comment]
@reecemcd This is great and super exciting! I'm looking through the code and trying to think of ways we can integrate this into our CI/CD pipeline similar to how the discord bots is integrated. It looks like heroku supports nestjs deployment, do you see any issues with that? I'm thinking for every PR that is created, a github action executes that will then upload the proposed code into the development environment for testing. It'll let anyone hit the swagger documentation, test the APIs etc. I have a similar system at my day job except there's much more steps that I would like to avoid altogether..

**Review by duke-eth — DISMISSED** [review]
This is fantastic @reecemcd. It is clean, well structured, and uses widely understood standards. We should apply some of these standards to our existing repos to improve the developer experience and make it easier to onboard new developers.

**Comment by reecemcd** [comment]
> @reecemcd This is great and super exciting! I'm looking through the code and trying to think of ways we can integrate this into our CI/CD pipeline similar to how the discord bots is integrated. It looks like heroku supports nestjs deployment, do you see any issues with that?

Heroku should be fine! If you try getting that going let me know if you have any questions and I can help optimize the Procfile.

>  I'm thinking for every PR that is created, a github action executes that will then upload the proposed code into the development environment for testing. It'll let anyone hit the swagger documentation, test the APIs etc. I have a similar system at my day job except there's much more steps that I would like to avoid altogether..

I'm not the biggest fan of having an "integration" style deployment so to speak as then anyone can wreck that test envs db with issues in their un-reviewed code. With enough time this will happen. Typically the expectation is you pull down a PR to test it if it's large enough that that is necessary and only deploy merges to the master/main branch. So the goal is to keep PRs as small as possible and continuously merge them as they are much easier to review. So in that scenario you just run tests, builds, and possibly even e2e/integration tests in the pipeline and they must pass before the merge is allowed.

Having said that, if that is how y'all do things today and like the way it works I'm down to test it out! One suggestion I would make to mitigate the potential issues I mentioned would be to maintain DB seeds and just wipe and re-seed that integration env DB with each deploy. I'll set those up for local dev anyways and we can test it out once the pipeline is in place. Good seeds then also make setting up reliable API e2e tests a breeze so win win win.

**Review by duke-eth — APPROVED** [review]

**Comment by amaredeus** [comment]
> > @reecemcd This is great and super exciting! I'm looking through the code and trying to think of ways we can integrate this into our CI/CD pipeline similar to how the discord bots is integrated. It looks like heroku supports nestjs deployment, do you see any issues with that?
> 
> 
> 
> @amaredeus Heroku should be fine! If you try getting that going let me know if you have any questions and I can help optimize the Procfile.
> 
> 
> 
> >  I'm thinking for every PR that is created, a github action executes that will then upload the proposed code into the development environment for testing. It'll let anyone hit the swagger documentation, test the APIs etc. I have a similar system at my day job except there's much more steps that I would like to avoid altogether..
> 
> 
> 
> I'm not the biggest fan of having an "integration" style deployment so to speak as then anyone can wreck that test envs db with issues in their un-reviewed code. With enough time this will happen. Typically the expectation is you (as a reviewer) pull down a PR to test it if it's large enough that that is necessary and only deploy merges to the master/main branch. So the goal is to keep PRs as small as possible and continuously merge them as they are much easier to review. So in that scenario you just run tests, builds, and possibly even e2e/integration tests in the pipeline and they must pass before the merge is allowed.
> 
> 
> 
> Having said that, if that is how y'all do things today and like the way it works I'm down to test it out! One suggestion I would make to mitigate the potential issues I mentioned would be to maintain DB seeds and just wipe and re-seed that integration env DB with each deploy. I'll set those up for local dev anyways and we can test it out once the pipeline is in place. Good seeds then also make setting up reliable API e2e tests a breeze so win win win.
> 
> 
> 
>  

Kind of.

So at the fintech place I work at we have multiple environments for the same API. They are

Production
Stage
Quality/Assurance
Development Approved
Development
Local

And further from these environments are split between two server locations with each respective URL. Pretty intense for a payment processing place 😅

For the bots we've just done
Production
Development approved
Local

We did have QA for a short time but almost no one used it so we opted to remove it to save time. 

I can take a look at how we can get a similar setup but I'd rather not destroy or build the db at all. For local it should be fine to destroy but for development approved it should be as close to production as can be where data is almost never destroyed since we'll be sharing that db.

**Comment by reecemcd** [comment]
> Kind of.
> 
> So at the fintech place I work at we have multiple environments for the same API. They are
> 
> Production Stage Quality/Assurance Development Approved Development Local
> 
> And further from these environments are split between two server locations with each respective URL. Pretty intense for a payment processing place 😅
> 
> For the bots we've just done Production Development approved Local
> 
> We did have QA for a short time but almost no one used it so we opted to remove it to save time.
> 
> I can take a look at how we can get a similar setup but I'd rather not destroy or build the db at all. For local it should be fine to destroy but for development approved it should be as close to production as can be where data is almost never destroyed since we'll be sharing that db.

OK I think we are on the same page here. Ideally here's how I think this should work if y'all are game to try out trunk based here (which is just more simple all around imo but achieves the same goals as gitflow):

- In PRs:
    - Github actions runs tests, builds, etc...
    - PR is approved
    - PR is merged to main

- On main:
    - Action runs on commits/merges to main auto deploy to dev

- To release:
    - When we are ready to release we cut a new version release with standard version.
    - Action runs on commits to main with release tags and deploys them to prod

**Comment by amaredeus** [comment]
> > Kind of.
> 
> > 
> 
> > So at the fintech place I work at we have multiple environments for the same API. They are
> 
> > 
> 
> > Production Stage Quality/Assurance Development Approved Development Local
> 
> > 
> 
> > And further from these environments are split between two server locations with each respective URL. Pretty intense for a payment processing place 😅
> 
> > 
> 
> > For the bots we've just done Production Development approved Local
> 
> > 
> 
> > We did have QA for a short time but almost no one used it so we opted to remove it to save time.
> 
> > 
> 
> > I can take a look at how we can get a similar setup but I'd rather not destroy or build the db at all. For local it should be fine to destroy but for development approved it should be as close to production as can be where data is almost never destroyed since we'll be sharing that db.
> 
> 
> 
> OK I think we are on the same page here. Ideally here's how I think this should work if y'all are game to try out trunk based here (which is just more simple all around imo but achieves the same goals as gitflow):
> 
> 
> 
> - In PRs:
> 
>     - Github actions runs tests, builds, etc...
> 
>     - PR is approved
> 
>     - PR is merged to main
> 
> 
> 
> - On main:
> 
>     - Action runs on commits/merges to main to auto deploy to dev
> 
> 
> 
> - To release:
> 
>     - When we are ready to release we cut a new version release with standard-version.
> 
>     - Action runs on commits to main with release tags and deploys them to prod
> 
> 
> 
> 

There was one issue with trunk based that came up during @duke-eth 's demo regarding hot fixes. The issue was having to manually sync back the branch into the main branch. I have terrible memory so for me I like that it's impossible to lose a hotfix deploy in git flow, since main is always in sync with production. 

Having said that, if this is a nonsensical issue then I'm all for it!

**Comment by reecemcd** [comment]
> The issue was having to manually sync back the branch into the main branch

I'm not sure what you mean by this?

> it's impossible to lose a hotfix deploy in git flow, since main is always in sync with production

In this flow main should always represent the latest version of the code. Don't merge something to main if it is going to break the build. If an old release needs a hotfix, branch it off from its tag and release that version from there and merge or cherry pick the change back to main when ready (this is essentially how every major open source library works). Releases are versioned, if you want to know what is deployed to a given env just look at the version of that release (or alternatively tag something like docker images by commit hash which doesn't apply here).

I think I see what you are getting at though and imo for this setup the best solution is to do deploys to prod via a manual CI trigger - aka just a button in github actions where you select the branch to deploy which is as close as you can git to promoting specific images to different envs in a more containerized setup. This allows you to deploy main as needed but also switch to deploying from an older version branch if needed for as long as needed. We could make this smart enough to get the best of both worlds there automation wise too.

**Comment by amaredeus** [comment]
> > The issue was having to manually sync back the branch into the main branch
> 
> I'm not sure what you mean by this?
> 
> > it's impossible to lose a hotfix deploy in git flow, since main is always in sync with production
> 
> In this flow main should always represent the latest version of the code. Don't merge something to main if it is going to break the build. If an old release needs a hotfix, branch it off from its tag and release that version from there and merge or cherry pick the change back to main when ready (this is essentially how every major open source library works). Releases are versioned, if you want to know what is deployed to a given env just look at the version of that release (or alternatively tag something like docker images by commit hash which doesn't apply here).
> 
> I think I see what you are getting at though and imo for this setup the best solution is to do deploys to prod via a manual CI trigger - aka just a button in github actions where you select the branch to deploy which is as close as you can git to promoting specific images to different envs in a more containerized setup. This allows you to deploy main as needed but also switch to deploying from an older version branch if needed for as long as needed. We could make this smart enough to get the best of both worlds there automation wise too.

100% agree, I'm in favor of keeping main up to date with what's in production as that's what we've been doing so far, however if you or anyone does feel strongly about a different development flow then feel free to create the PRs and demos for the team so that they are aware of what's going on.

**Comment by amaredeus** [comment]
Works very nicely 
Screen Shot 2021-12-27 at 2 27 41 PM

Looking forward to getting this integrated into CI/CD pipelines! Thank you @reecemcd for all the work

**Review by amaredeus — APPROVED** [review]

**Comment by amaredeus** [comment]
Merging as this is working!

**Pull request merged**
